---
ID: "577c1425-e4ba-40ce-bc92-97875bfd4e56"
Parent: "45b039a4-d895-47c7-9a30-21ab882774e5"
Template: "aa977b10-c924-4446-8b15-a7d26aa6c93f"
Path: /sitecore/content/OneWeb/Default/Home/Development/Product Description
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{1C073FDC-E9C0-459F-8E99-1B65C3F930FE}"
              p:before="*"
              s:ds="{577C1425-E4BA-40CE-BC92-97875BFD4E56}"
              s:id="{8B0393E9-EE25-4F0B-A5FD-777B3AD2C737}"
              s:par="Reset Caching Options&amp;GridParameters=%7B908E2BC6-C110-4ED7-AF39-7EEACBB31A34%7D&amp;FieldNames=%7B58D02E15-9547-4883-BFF1-EFE4E2374B47%7D&amp;Styles&amp;RenderingIdentifier&amp;DynamicPlaceholderId=1"
              s:ph="/main/container-2/column-2-3"
              s:ccb="Clear on publish" />
            <r
              uid="{47BBFA72-2E56-44AB-AD6F-D2C7038FBBC2}"
              p:after="r[@uid='{1C073FDC-E9C0-459F-8E99-1B65C3F930FE}']"
              s:ds=""
              s:id="{C25766C8-9AFD-4D28-87FE-147774F6806D}"
              s:par="ColumnWidth1=%7B908E2BC6-C110-4ED7-AF39-7EEACBB31A34%7D%7C%7BC417AE43-BBE2-4B58-9B43-A125B3013ADE%7D%7C%7B03EA3C58-9F87-41D5-95D6-4B899C88572E%7D&amp;ColumnWidth2=%7B908E2BC6-C110-4ED7-AF39-7EEACBB31A34%7D%7C%7BC417AE43-BBE2-4B58-9B43-A125B3013ADE%7D%7C%7B03EA3C58-9F87-41D5-95D6-4B899C88572E%7D&amp;ColumnWidth3&amp;ColumnWidth4&amp;ColumnWidth5&amp;ColumnWidth6&amp;ColumnWidth7&amp;ColumnWidth8&amp;Reset Caching Options&amp;SplitterSize=2&amp;EnabledPlaceholders=1%2C2&amp;Styles1&amp;Styles2&amp;Styles3&amp;Styles4&amp;Styles5&amp;Styles6&amp;Styles7&amp;Styles8&amp;DynamicPlaceholderId=3"
              s:ph="/main/container-2"
              s:ccb="Clear on publish" />
            <r
              uid="{757A98D3-BD26-478F-9FEB-DB780B495435}"
              p:after="*[1=2]"
              s:id="{896A2C68-1362-4E88-8BA0-1805AE6D4837}"
              s:par="Reset Caching Options&amp;GridParameters&amp;BackgroundImage&amp;Styles&amp;CacheClearingBehavior=Clear%20on%20publish&amp;RenderingIdentifier&amp;DynamicPlaceholderId=2"
              s:ph="main" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220321T093319Z
    - ID: "4c2f221f-9426-45ed-9eeb-c79bb3169565"
      Hint: StickyNotes
      Value: |
        {"items":[]}
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Product Description
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "625f32a7-8b24-4b35-8f6f-1464da77bc40"
      Hint: Content
      Value: |
        <span style="background-color: #ffffff; color: #595a5c;">The Strong Chew Braided Dog Ring chew toy provides a fun chewing experience that will keep your fur friend busy and entertained. Made of strong natural rubber, this tough dog chew toy is perfect for pets who love some flex &amp; give and encourages healthy, non-destructive chewing habits. You can also roll this round chew toy and watch your dog chase it for extra excitement. The braided shape with unique raised textures will keep your dog's attention while helping clean teeth&nbsp; and freshening breath through chewing action. Keep your best friend's chewing fun going with this satisfying chew toy!</span>
    - ID: "8ccbb921-d330-4712-95b3-f77a0ff02cb4"
      Hint: Title
      Value: Strong Chew Braided Dog Ring Chew Toy
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7f7c4a8a-6b9b-47d6-97d7-d0620a2ab62d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220323T063842Z
