---
ID: "55d13a94-c9cf-4aaf-ac8d-463d4be5fe27"
Parent: "c347f38a-ac79-4dce-aad6-30b59bbc3845"
Template: "ea8a3f26-9ccd-443a-95f5-71b868a94bd0"
Path: /sitecore/system/Settings/Feature/OneWeb/Product Variant/Product Variant Site Setup/Rendering Variants/Product Variant
SharedFields:
- ID: "4795a7c6-08a9-4248-86c3-d460062c3a22"
  Hint: Location
  Value: "{5CDC5EB2-F14F-4495-88E8-AA882DDFAA05}"
- ID: "7868e6bc-525c-4fce-ab8a-77da3e09b171"
  Hint: Name
  Value: Product Variant
- ID: "ad0e8de7-f6c1-49fa-b2c4-87e10fbdaa52"
  Hint: Fields
  Value: __Icon=Office%2F32x32%2Fwindow_dialog.png
- ID: "e62c28f0-9d3b-46e2-8bec-a5e120542499"
  Hint: Template
  Value: "{2EDA4C9B-E832-4C65-86D2-E0141DCA351C}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160713T064438Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e4c377dd-e07c-47c1-8477-ba7b33fedfac"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220328T093635Z
