---
ID: "408c637a-ef04-4779-8ed2-812dd0cf2a8d"
Parent: "a83c1b9d-ed47-4117-836d-9e5abec25209"
Template: "0339bac0-78c1-43c1-b930-f8c26a5fdf80"
Path: /sitecore/content/OneWeb/Default/Presentation/Placeholder Settings/Product Detail Shell
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220413T112127Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "64afe477-06ad-419a-9b65-8904e851205c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220413T112422Z
