---
ID: "334c6a15-2afa-4db9-a768-3f71a80a9665"
Parent: "bc41b87d-2a9b-4689-9f51-80bb5b31a6e7"
Template: "bc41b87d-2a9b-4689-9f51-80bb5b31a6e7"
Path: /sitecore/templates/Project/OneWeb/Default/Pages/Product/Product Details Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{F9CF5C04-01C3-4060-A143-1E12421C09BE}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220320T183848Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "42ec0458-b16f-4df4-a2e4-656c45eeaae3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220324T121753Z
