---
ID: "41fe3d1f-dc38-414e-8b04-ed76bf8542f1"
Parent: "dc5253c2-b311-4bed-824d-adb0ca25e3ee"
Template: "dc5253c2-b311-4bed-824d-adb0ca25e3ee"
Path: /sitecore/templates/Feature/OneWeb/Header Global Menu/Rendering Parameters/HeaderGlobalMenu/__Standard Values
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20111207T111100
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ce453cf7-32be-4cac-a679-939fd5fd54d1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220218T114112Z
