---
ID: "99045921-b17f-4e2c-831d-6503c4461f80"
Parent: "25fa2ac0-006a-460f-9241-db489cd2a63c"
Template: "25fa2ac0-006a-460f-9241-db489cd2a63c"
Path: /sitecore/templates/Feature/OneWeb/Header Shell/Rendering Parameters/Header Shell/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220217T074405Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f3b09777-eae7-4c95-ba4e-ea476727144a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220217T074405Z
