---
ID: "e02e4dbb-55b3-427e-815f-3a5f4966bc3d"
Parent: "c3eef3c4-d454-4d74-8caa-ec50f4fe7930"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/templates/Branches/Feature/OneWeb/SEO/Default Page Script Variant/$name/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160427T134629Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9c950ee6-a5fb-43f5-be39-1995e3fad550"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220309T113954Z
