---
ID: "cc11ce96-380f-4527-a1d5-5d7c1f9a7a37"
Parent: "270675cf-883b-4333-b86d-7bac3ee80d67"
Template: "270675cf-883b-4333-b86d-7bac3ee80d67"
Path: /sitecore/templates/Feature/OneWeb/Multi Column Content Tiles/Multi Column Content Tiles/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{2F7BFE05-BDD4-47AD-844F-3E3997EDA6B4}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220218T122824Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "72ff1e64-f37a-4b14-a111-527942cbf78a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220218T122836Z
