---
ID: "1e8390b0-6166-4e1e-81e2-fbede861c90f"
Parent: "6e02d2bf-03d4-46a6-86ed-1f258a343651"
Template: "01e8f9bf-c9a6-4d92-9770-afcbd6491464"
Path: /sitecore/content/OneWeb/Default/Global Data/SeoSchema/Product Schema
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220322T071830Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a16473e2-6d18-4b61-ab79-2b66a450a052"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220322T101010Z
