---
ID: "75feaa54-e481-4642-a4b1-1cec29ac89ca"
Parent: "4d38ae0e-d6ce-4eb0-bf8f-ac9fd022fc85"
Template: "4d38ae0e-d6ce-4eb0-bf8f-ac9fd022fc85"
Path: /sitecore/templates/Feature/OneWeb/Hubspot Form/Hubspot Form Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {B1F28930-86EC-4B4B-BC44-5DAE936DE9EC}
    {4D38AE0E-D6CE-4EB0-BF8F-AC9FD022FC85}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "28e6c0cb-2739-443e-8840-8c3315185670"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220207T113901Z
